---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: database-destination
  namespace: dokuwiki 
spec:
  rsync:
    copyMethod: Snapshot 
    storageClassName: ocs-storagecluster-ceph-rbd
    volumeSnapshotClassName: ocs-storagecluster-rbdplugin-snapclass 
    capacity: 2Gi
    accessModes: [ReadWriteOnce]
