---
apiVersion: scribe.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source 
  namespace: dokuwiki 
spec:
  sourcePVC: dokuwiki
  trigger:
    schedule: "*/3 * * * *"
  rsync:
    sshKeys: scribe-rsync-dest-src-database-destination
    address: 172.32.106.72
    copyMethod: Snapshot
    volumeSnapshotClassName: gp2-csi
