apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: file 
  namespace: scribe-system
spec:
  type: GitHub
  pathname: https://github.com/cooktheryan/twitch-scribe-rhacm.git
